# Generated by Django 2.0.1 on 2021-02-20 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20180926_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(max_length=32, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=32, verbose_name='菜单'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(blank=True, help_text='nul表示不是菜单;非null表示不是菜单', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbac.Menu', verbose_name='二级菜单'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='URL的别名'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, help_text='对于非菜单的权限需要选择一个可以成为菜单的权限', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbac.Permission', verbose_name='关联权限'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='角色名称'),
        ),
    ]
